### PR TITLE
Facturation 2

### PR DESCRIPTION
**Pull request by drosofff**
Closing Facturation PR and reopening Facturation 2 after GitHub crashed (22:10:2018)

- This PR is an extension of the closed PR from the facturation branch.
- Here facturation.xml is developed to run locally in root/tools directory (.shed.yml was moved to `.shed.yml.local` to escape travis/planemo tests
- condafication is prepared but not executing properly (to do latter if beneficial)
- a requirements.txt file is provided which allows to install easily python module (py27) using the command
```
pip install -r requirements.txt
```
- The tools was installed successfully in lbcd41.snv.jussieu.fr as well as in a GalaxyKickStart instance. Basically, what has to be done is (i) copy the tool folder in root/tools (ii) edit the appropriate tool_conf.xml file to indicate the relative pathway to the tool (iii) restart the galaxy instance

### To be fixed

- [x] There is a parsing bug: values of prices have in some instances an extra space which causes error in the formula calculation of the generated xlsx file.

- [x] The parsing is poorly annotated, which makes the code very difficult to maintain in the future. There is probably more simple / transparent coding (with less dependency modules).

- [x] Squash commits before merging !

### Note before merging

Eventually, this PR is compliant to conda packaging. Pip can still be used in combination with the requirements.txt, but the conda environment is better isolated. The code is still very weak with regard to its dependency to changes in the templates to be parsed (and note object oriented). But it works and it is enough !

### CODE REVIEW

**Comment by drosofff** [comment]
@michelraymond the tests are now passing, including with condafication ! Yet GitHub seems still sick and I will profit from the time before recovery to squash the numerous commits of this PR !

**Comment by drosofff** [comment]
Ping @michelraymond for your review and feedback

**Comment by drosofff** [comment]
@michelraymond 
> Editing the galaxy parser should do the trick, but it limits the portability of the script.

What do you mean by "Editing the galaxy parser" ?

**Comment by michelraymond** [comment]
Sorry, the galaxy sniffer.

**Comment by drosofff** [comment]
> Sorry, the galaxy sniffer.

OK, lets keep this for the next step. I'll merge !

**Pull request merged**
