### PR TITLE
Skip failed k-mers with oases

### PR DESCRIPTION
**Pull request by mvdbeek**
Occasionally specific k-mers fail at random when assembling with oases/velvet.
If this is the case, we skip that k-mer and continue the assembly. Also bump
the tool version and and reformat wrapper xml to 4 space indentation, add
citation and fix help syntax errors.

### CODE REVIEW

**Comment by mvdbeek** [comment]
@drosofff @JuPeg I tested this with planemo, I guess this would make the tool more robust.

**Comment by JuPeg** [comment]
I tested with datasets that were failing with previous version and now it works fine!

**Comment by mvdbeek** [comment]
@drosofff should we give this a try? I think this will prevent a lot of frustration when running on larger datasets.

**Comment by drosofff** [comment]
Yes, I will check also, and we need a list of what has to be updated in addition (tool list in ansible, toolshed suite, tool shed workflows, etc...). Start to be complicated to maintain isn't it ?

**Pull request merged**
