### PR TITLE
Removed 'edat' from retrieve because it is only available for pubmed

### PR DESCRIPTION
**Pull request by ccedmendoza**
Since we only use the nuccore and prot databases 'edat' is useless in this case

### CODE REVIEW

**Comment by drosofff** [comment]
What do you mean by "only available for pubmed" ?

**Comment by ccedmendoza** [comment]
It is only available for the pubmed database and not the nuccore or prot databases.

**Comment by drosofff** [comment]
Ah Ok !

**Comment by drosofff** [comment]
Can you bump the tool to 2.0.1 ?

**Pull request merged**
