### PR TITLE
Add nested collection concatenation

### PR DESCRIPTION
**Pull request by ccedmendoza**

### CODE REVIEW

**Comment by ccedmendoza** [comment]
The help section still needs to be updated

**Comment by drosofff** [comment]
> The help section still needs to be updated

Ok, seen it !

**Comment by ccedmendoza** [comment]
Still needs some work :

- It won't work when the nested list to be concatenated has more than 1 level
  - to solve this I'll try changing the discovery of datasets to a json aproach and write the json file while the tool runs

**Comment by ccedmendoza** [comment]
@drosofff if you're ok with this tool it's ready to merge

**Comment by drosofff** [comment]
@ccedmendoza ok, give me 20 min for a brief review

**Comment by ccedmendoza** [comment]
manually tested the concatenations and fixed bugs. For me the tool is ready to be merged

**Comment by drosofff** [comment]
Go for it ! :+1:

Christophe Antoniewski

ARTbio <http://artbio.fr/> - Tel +33 1 44 2*7 70 05*
Mobile +33 6 68 60 51 50
https://twitter.com/ARTbio_IBPS


Le mar. 18 juin 2019 à 17:07, ccedmendoza <notifications@github.com> a
écrit :

**Pull request merged**
